### ISSUE TITLE
project build error

### ISSUE THREAD

**Issue by regholl** [zackjohnson8/StockWatch#38]
[{
	"resource": "/E:/StockWatch/.teamcity/pom.xml",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "0",
	"severity": 8,
	"message": "Project build error: Non-resolvable parent POM for Python_StockWatch:Python_StockWatch_dsl:1.0-SNAPSHOT: ...:pom.xml:pom:.. failed to transfer from http://10.0.0.194:8111/app/dsl-plugins-repository during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of teamcity-server has elapsed or updates are forced. Original error: Could not transfer artifact ...:pom.xml:pom:.. from/to teamcity-server (http://10.0.0.194:8111/app/dsl-plugins-repository): Connect timed out and 'parent.relativePath' points at wrong local POM",
	"source": "Java",
	"startLineNumber": 9,
	"startColumn": 2,
	"endLineNumber": 9,
	"endColumn": 11
}]
	"

**Comment by zackjohnson8** [comment]
Sorry I hadn't noticed this previously. Did you ever figure this out?

**Comment by regholl** [comment]
no i didn't and i ran you new code and here are the results

Traceback (most recent call last):
  File "e:\StockWatch\src\stock_watch\__main__.py", line 3, in <module>
    from src.stock_watch.app import StockWatch
  File "e:\stockwatch\src\stock_watch\__init__.py", line 22, in <module>
    DATABASE_CREDENTIALS = get_database_configs()
  File "e:\stockwatch\src\stock_watch\helpers.py", line 45, in
get_database_configs
    host=check_value(config['database']['host']),
KeyError: 'host'

i believe you left out host in Startup_config.yml
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "e:\StockWatch\src\stock_watch\__main__.py", line 4, in <module>
    from . import helpers
ImportError: attempted relative import with no known parent package

this one i'm still back tracking.

also even though this is in docker i still have to run a virtualenv correct?

**Comment by zackjohnson8** [comment]
I believe it's working correctly. You've changed the information inside the startup_config.yml file correct? For database, I'm currently just using (name: stockdata, user: stockdata, host: localhost, password: mysecretpassword) during development.
![image](https://user-images.githubusercontent.com/18540777/205129256-d2143ff6-e103-4a15-b560-dfa442630682.png)

Yea, still run in virtual environment. This project makes use of docker but nothing setup for running inside docker, if that makes sense.

**Comment by zackjohnson8** [comment]
To get the TDAmeritrade information you'll need to follow [](https://developer.tdameritrade.com/content/authentication-faq)

**Comment by zackjohnson8** [comment]
I'll update the README.md to link the faq locations for this TDAmeritrade and the ./src/stock_watch/data_scraper/configs/praw.ini reddit stuff too. I wanted to make this program general use to anyone, so I can't provide my api information for any of these apps. There's probably a better way to log this information out if you'd like taking that on?

**Comment by zackjohnson8** [comment]
You've encouraged me to make a few changes. I've updated the Getting Started section of the README.md to have a better setup guide https://github.com/zackjohnson8/StockWatch#getting-started. This project should probably remove the hard need for specific API's unless attempting to use them. I'll create an issue for it so that anyone can build and run the project, but will be notified that specified sections won't work until implemented.

**Comment by regholl** [comment]
also a little extra info in build.kts about the patch,i'm still not sure if
i put "id" in the right place(s)

**Comment by zackjohnson8** [comment]
Ya, I haven't updated the kts stuff in awhile. Brought down my local TeamCity server recently and haven't bothered with it since.
