### ISSUE TITLE
Docker failed cli up command after initial successful run

### ISSUE THREAD

**Issue by zackjohnson8** [zackjohnson8/StockWatch#53]
![image](https://user-images.githubusercontent.com/18540777/206545925-be5168b3-fe8e-461f-8a58-3fb5b6f79524.png)

**Comment by regholl** [comment]
i can;t believe in 9 months all of this great work might be obsolete.just
the thought of TDA moving over to scwab makes me want to move my assets to
Alpaca

**Comment by zackjohnson8** [comment]
Not if we do this right. Even if TDAmeritrade removed all API functionality, the goal is to build this software so that we'd only need to rewrite the logic inside a wrapper that consumes TDA API. I mean, trading through an API is the easiest part of this. The same goes for scraping and analyzing the data, we want everything to still "run" even if one section dropped out. I haven't asked, but what is your goal with programming stock software?

**Comment by regholl** [comment]
i didnt think about it that way,the logic will still be useful.i mainly use
it just so i don;t trade on emotion.it's my speed bump.

**Comment by zackjohnson8** [comment]
Exactly, emotional trading is bad trading. With enough data, I'm hoping to get a better picture of what the market is expected to do. You can't just rely on a single form of trading these days. There's no way we'll take all manual trading out with a single program, but I want to manage risk. I want automatic stop losses placed on every trade to manage loss potentials, fast information on stock movement, and a large amount of data flowing in from as many sources as possible to look at the data myself and AI to determine the market consensus on the topic. Still got a lot to do before any of that comes into play.
