### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by zackjohnson8** [zackjohnson8/StockWatch#68]
The current terminal design of output/input won't suffice if this program gets any more complicated.

- [ ] Find a cross-platform desktop GUI solution for future scaling of the app.
- [ ] Implement a prototype that outputs the data retrieved by the data scraper service

**Comment by regholl** [comment]
HAPPY NEY YEAR,
i just grabbed the latest copy of stockwatch and it seems to be hung up on
starting retrieval loop for REDDITscraper

#1 transferring dockerfile: 76B done
#1 DONE 1.0s

#2 [stockwatch-adminer internal] load .dockerignore
#2 transferring context: 34B done
#2 ...

#3 [stockwatch-database internal] load build definition from
postgres_database.Dockerfile
#3 transferring dockerfile: 299B done
#3 DONE 1.2s

#2 [stockwatch-adminer internal] load .dockerignore
#2 DONE 1.5s

#4 [stockwatch-database internal] load .dockerignore
#4 transferring context: 34B done
#4 DONE 1.6s

#5 [stockwatch-adminer internal] load metadata for
docker.io/library/adminer:4.8.1
#5 ...

#6 [auth] library/adminer:pull token for registry-1.docker.io
#6 DONE 0.0s

#7 [auth] library/postgres:pull token for registry-1.docker.io
#7 DONE 0.0s

#8 [stockwatch-database internal] load metadata for
docker.io/library/postgres:14.5-bullseye
#8 DONE 1.6s

#5 [stockwatch-adminer internal] load metadata for
docker.io/library/adminer:4.8.1
#5 DONE 2.0s
#12 ...

#13 [stockwatch-database 2/2] COPY create_db.sql
/docker-entrypoint-initdb.d/
#13 CACHED

#12 [stockwatch-database] exporting to image
#12 exporting layers done
#12 writing image
sha256:7d82224659dc69302c00f0ffbfcd33b5099f32a7eb3d747930aee061aa01e1f0
#12 writing image
sha256:7d82224659dc69302c00f0ffbfcd33b5099f32a7eb3d747930aee061aa01e1f0
0.1s done
#12 naming to docker.io/library/stockwatch-adminer done
#12 writing image
sha256:bc104befc825c87951de03697cd1c95c4637918bbb93a9f1d1a4b29b594cb3a8
#12 writing image
sha256:bc104befc825c87951de03697cd1c95c4637918bbb93a9f1d1a4b29b594cb3a8
0.1s done
#12 naming to docker.io/library/stockwatch-database done
#12 DONE 1.7s
Completed work on chunk 1/1
2023-01-01 11:45:27,409-INFO-root::scraper_process|28:: Started
RedditScraper
2023-01-01 11:45:29,407-INFO-root::reddit_scraper|65:: Starting the
retrieval loop for the RedditScraper...

**Comment by zackjohnson8** [comment]
It's not actually stuck. In this newest update I've changed a lot of stuff with message bus, data scraping (RedditScraper), and added the PyQt GUI, which I hope is opening for you atleast. I've stopped posting messages to the command line until I've added something to communicate the information to the PyQt GUI (some sort of flask API communication between the backend and that frontend).

**Comment by zackjohnson8** [comment]
I'll see if I can add in a quick logging.info to get that logging until a later date.

**Comment by regholl** [comment]
Ok then,all is well because it did open

**Comment by zackjohnson8** [comment]
Fix it to log the message until the GUI is complete. Thanks Reginald :)
