### ISSUE TITLE
docker sluggish

### ISSUE THREAD

**Issue by regholl** [zackjohnson8/StockWatch#69]
any work arounds to speed up docker desktop?mine gets stuck on starting very frequently,yes i have uninstalled and reinstalled it.

**Comment by zackjohnson8** [comment]
If you are talking about Docker Desktop the application, then I wouldn't actually know. My main development OS is Linux so I don't actually use Windows very often. Even running StockWatch on Windows there's a noticeable difference in performance with Docker.

**Comment by regholl** [comment]
yeah it's the desktop,i'm in the beginnings of writing my own stock program
since i learned a lot from you but docker isn't cooperating so i may just
switch to mongo.

**Comment by zackjohnson8** [comment]
Not the end of the world. I like the portability of Docker to launch a database on any machine I'm running my program. Docker isn't the database itself but the tool used to create it. StockWatch's database is actually PostgreSQL. I mean it wouldn't be the worst thing to manually create a database like Mongo.
